apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: expressjs-k8s
  namespace: expressjs-k8s
spec:
  releaseName: expressjs-k8s
  chart:
    spec:
      chart: expressjs-k8s
      sourceRef:
        kind: HelmRepository
        name: expressjs-k8s
        namespace: expressjs-k8s
  interval: 10m
  livenessProbe:
    httpGet:
      path: /links
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
  values:
    ingress:
        enabled: false
