apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: expressjs-k8s
  namespace: expressjs-k8s
spec:
  releaseName: expressjs-k8s
  chart:
    spec:
      chart: expressjs-k8s
      sourceRef:
        kind: HelmRepository
        name: expressjs-k8s
        namespace: expressjs-k8s
  interval: 10m
  values:
    ingress:
      enabled: false
    container:
      livenessProbe:
        httpGet:
          path: /links
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
